/*
 * KovitoBoard
 * Copyright (C) 2026 Anode LLC
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
/**
 * Unit tests for `src/server/trust-prompt-respond-dedup.ts`.
 *
 * Verifies the normative behaviour declared in
 * `docs/specs/trust-prompt-relay.md` v1.5 §8.1.1 (supplementary §S20, v0.2.0):
 *
 *   - Duplicate `(windowName, promptId)` within TTL → claim returns false.
 *   - Distinct identifiers do not collide on either dimension.
 *   - Entries past TTL are reclaimable as new claims.
 *   - Size cap (1024) evicts the oldest insertion-order entry.
 *   - Duplicate detection runs BEFORE eviction, so a duplicate flood on a
 *     single key cannot evict legitimate older entries (DoS resistance).
 *
 * Tests use the `_setNowProviderForTests` virtual-clock hook so TTL elapse
 * can be exercised without sleeping. The `_resetTrustDedupLedgerForTests`
 * hook isolates each case.
 */

import { describe, it, expect, beforeEach } from 'vitest'

import {
  tryClaimTrustResponded,
  releaseTrustClaim,
  TRUST_DEDUP_TTL_MS,
  TRUST_DEDUP_MAX_ENTRIES,
  _resetTrustDedupLedgerForTests,
  _setNowProviderForTests,
  _getTrustDedupLedgerSizeForTests,
} from '../../src/server/trust-prompt-respond-dedup'

// ----- Virtual clock helper ---------------------------------------------

let virtualNow = 0

function setVirtualNow(ms: number): void {
  virtualNow = ms
}

function advanceVirtualNow(deltaMs: number): void {
  virtualNow += deltaMs
}

beforeEach(() => {
  _resetTrustDedupLedgerForTests()
  virtualNow = 1_000_000 // arbitrary nonzero epoch
  _setNowProviderForTests(() => virtualNow)
})

// =========================================================================
// Basic duplicate detection
// =========================================================================

describe('tryClaimTrustResponded — basic duplicate detection', () => {
  it('first claim on a fresh ledger returns true', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })

  it('same (windowName, promptId) claimed twice within TTL → second returns false', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(false)
    // The duplicate must not have grown the ledger.
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })

  it('same key claimed three times → only the first returns true', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(false)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(false)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })
})

// =========================================================================
// Key dimensions: windowName and promptId both participate
// =========================================================================

describe('tryClaimTrustResponded — key dimensions', () => {
  it('different windowName, same promptId → both succeed', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(tryClaimTrustResponded('win-b', 'prompt-1')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(2)
  })

  it('same windowName, different promptId → both succeed', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(tryClaimTrustResponded('win-a', 'prompt-2')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(2)
  })

  // Note: the spec ("§8.1.1 ledger characteristics: key is `(windowName,
  // promptId)` pair, string concatenation is an implementation detail")
  // does not require the encoding to be unambiguous against adversarial
  // separator-embedding inputs. Production callers are constrained:
  //   - `windowName` is a tmux window identifier, which tmux restricts to
  //     a safe character set (no control bytes).
  //   - `promptId` is generated by `randomUUID()` (hex characters only).
  // Both input sets exclude the `\x1f` Unit Separator used internally, so
  // a collision via embedded separators is not reachable from a legitimate
  // caller. We do not test that boundary.
})

// =========================================================================
// TTL behaviour
// =========================================================================

describe('tryClaimTrustResponded — TTL expiration', () => {
  it('re-claim strictly within TTL → false (the active entry is still live)', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    advanceVirtualNow(TRUST_DEDUP_TTL_MS - 1)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(false)
  })

  it('re-claim at exactly TTL → true (spec: "5 分以上" is inclusive at the boundary)', () => {
    // The implementation uses `now - existing < TTL` so `now - existing
    // === TTL` is already "expired" and a fresh claim succeeds.
    // Spec wording: "5 分以上開けた同一 promptId 再 claim は新規扱い".
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    advanceVirtualNow(TRUST_DEDUP_TTL_MS)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    // The expired entry is removed during the eviction phase of the second
    // claim, leaving exactly one live entry (the new one).
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })

  it('re-claim strictly past TTL → true (the slot is treated as vacant)', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    advanceVirtualNow(TRUST_DEDUP_TTL_MS + 1)
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })

  it('expired entries are reaped during a claim of a different key (eviction phase 2a)', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
    advanceVirtualNow(TRUST_DEDUP_TTL_MS + 1)
    expect(tryClaimTrustResponded('win-b', 'prompt-2')).toBe(true)
    // The expired (win-a, prompt-1) entry should have been swept by the
    // TTL eviction sub-phase before the new entry was inserted.
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })
})

// =========================================================================
// Cap behaviour
// =========================================================================

describe('tryClaimTrustResponded — size cap eviction', () => {
  it('ledger size never exceeds TRUST_DEDUP_MAX_ENTRIES', () => {
    // Insert one more than the cap with distinct keys. The cap should hold.
    for (let i = 0; i < TRUST_DEDUP_MAX_ENTRIES + 100; i++) {
      const ok = tryClaimTrustResponded('win', `prompt-${i}`)
      expect(ok).toBe(true)
    }
    expect(_getTrustDedupLedgerSizeForTests()).toBe(TRUST_DEDUP_MAX_ENTRIES)
  })

  it('cap eviction holds the ledger at MAX_ENTRIES on overflow', () => {
    // Fill the cap exactly.
    for (let i = 0; i < TRUST_DEDUP_MAX_ENTRIES; i++) {
      expect(tryClaimTrustResponded('win', `prompt-${i}`)).toBe(true)
    }
    expect(_getTrustDedupLedgerSizeForTests()).toBe(TRUST_DEDUP_MAX_ENTRIES)

    // One more legitimate claim — the cap holds, the new entry is in.
    expect(tryClaimTrustResponded('win', 'prompt-overflow')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(TRUST_DEDUP_MAX_ENTRIES)
  })

  it('cap eviction frees the oldest slot (prompt-0 reclaimable after one overflow)', () => {
    // Fill the cap and overflow by one. The oldest (prompt-0) should be the
    // eviction victim.
    for (let i = 0; i < TRUST_DEDUP_MAX_ENTRIES; i++) {
      expect(tryClaimTrustResponded('win', `prompt-${i}`)).toBe(true)
    }
    expect(tryClaimTrustResponded('win', 'prompt-overflow')).toBe(true)

    // The oldest slot is now vacant — re-claiming it succeeds.
    //
    // Caveat: this re-claim itself triggers another cap-eviction round
    // (the ledger is at cap when this call enters Phase 2b), which will
    // evict the new oldest (`prompt-1`). The test asserts only the
    // re-claim succeeding; the next-oldest's status is exercised in the
    // sibling test below to keep observations independent.
    expect(tryClaimTrustResponded('win', 'prompt-0')).toBe(true)
  })

  it('cap eviction spares the recently-inserted entries (the eviction victim is the *oldest*)', () => {
    // Same setup: fill + overflow by one.
    for (let i = 0; i < TRUST_DEDUP_MAX_ENTRIES; i++) {
      expect(tryClaimTrustResponded('win', `prompt-${i}`)).toBe(true)
    }
    expect(tryClaimTrustResponded('win', 'prompt-overflow')).toBe(true)

    // Without triggering any further mutation, verify that the new tail
    // (`prompt-overflow`) and the second-oldest (`prompt-1`, which would
    // be next in line for eviction but has not yet been evicted) are
    // both still locked. Each duplicate-detection return below is Phase
    // 1 only — no Phase 2/3 mutation occurs, so the ledger state is
    // preserved across these assertions.
    expect(tryClaimTrustResponded('win', 'prompt-overflow')).toBe(false)
    expect(tryClaimTrustResponded('win', 'prompt-1')).toBe(false)
    expect(tryClaimTrustResponded('win', `prompt-${TRUST_DEDUP_MAX_ENTRIES - 1}`)).toBe(false)
  })
})

// =========================================================================
// Rollback — releaseTrustClaim makes a slot reclaimable
// =========================================================================

describe('releaseTrustClaim — handler rollback path', () => {
  // The handler in `index.ts` calls `releaseTrustClaim` after Phase 4
  // (detector dispatch) returns false — meaning no tmux keystroke was
  // delivered, so the slot is safe to vacate so a buggy / hostile client
  // that sent a shape-valid but semantically invalid response (unknown
  // choiceId, TOCTOU promptId mismatch, etc.) cannot occupy the slot for
  // the full TTL window and DoS the legitimate next respond.

  it('release after a successful claim makes the slot reclaimable immediately', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    // Without release, the very next claim is rejected as a duplicate.
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(false)

    releaseTrustClaim('win-a', 'prompt-1')
    expect(_getTrustDedupLedgerSizeForTests()).toBe(0)

    // After release, the same (windowName, promptId) is claimable again
    // even though no TTL elapsed.
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(1)
  })

  it('release does not affect other entries', () => {
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
    expect(tryClaimTrustResponded('win-b', 'prompt-2')).toBe(true)
    expect(tryClaimTrustResponded('win-a', 'prompt-3')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(3)

    // Roll back only the first.
    releaseTrustClaim('win-a', 'prompt-1')
    expect(_getTrustDedupLedgerSizeForTests()).toBe(2)

    // The other two entries still lock.
    expect(tryClaimTrustResponded('win-b', 'prompt-2')).toBe(false)
    expect(tryClaimTrustResponded('win-a', 'prompt-3')).toBe(false)
    // And the released one is reclaimable.
    expect(tryClaimTrustResponded('win-a', 'prompt-1')).toBe(true)
  })

  it('release of a never-claimed slot is a harmless no-op', () => {
    // Calling release without a matching successful claim should not
    // throw; it simply observes a missing entry and returns.
    expect(() => releaseTrustClaim('win-a', 'never-claimed')).not.toThrow()
    expect(_getTrustDedupLedgerSizeForTests()).toBe(0)
  })

  it('release-then-re-claim cannot be exploited as a duplicate-flood DoS', () => {
    // Plant two legitimate older entries.
    expect(tryClaimTrustResponded('win-x', 'legit-1')).toBe(true)
    expect(tryClaimTrustResponded('win-y', 'legit-2')).toBe(true)

    // Imagine a hostile client that hammers (claim → release → claim → ...)
    // on a single key. Each release vacates the slot, but the cycle does
    // NOT inflate the ledger past 1 entry for that key, and does NOT
    // evict legitimate older entries (the size cap is nowhere near
    // triggered — at most 3 entries live at any moment).
    for (let i = 0; i < 1024; i++) {
      expect(tryClaimTrustResponded('win-hostile', 'p')).toBe(true)
      releaseTrustClaim('win-hostile', 'p')
    }

    // Legitimate entries still locked.
    expect(tryClaimTrustResponded('win-x', 'legit-1')).toBe(false)
    expect(tryClaimTrustResponded('win-y', 'legit-2')).toBe(false)
    // Ledger holds exactly the two legitimate entries (hostile released
    // its own claim each iteration).
    expect(_getTrustDedupLedgerSizeForTests()).toBe(2)
  })
})

// =========================================================================
// DoS resistance — duplicate flood does not evict legitimate entries
// =========================================================================

describe('tryClaimTrustResponded — duplicate flood does not evict legitimate older entries', () => {
  it('repeated claims on the same key never insert and never evict', () => {
    // Plant a small set of legitimate older entries.
    expect(tryClaimTrustResponded('win-a', 'oldest')).toBe(true)
    expect(tryClaimTrustResponded('win-b', 'middle')).toBe(true)
    expect(tryClaimTrustResponded('win-c', 'newest')).toBe(true)
    expect(_getTrustDedupLedgerSizeForTests()).toBe(3)

    // Now flood with duplicates of a single new key. The spec mandates that
    // duplicate detection runs BEFORE the eviction phase, so none of these
    // attempts should mutate the ledger — `(win-flood, prompt-flood)` was
    // never accepted in the first place because the first attempt itself
    // was a duplicate of nothing (so it WOULD be accepted normally)...
    //
    // Rebuild the scenario more precisely: we want to show that after a
    // legitimate first claim, a flood of duplicates on that same key
    // does not insert 1024 new entries (which would evict our older legit
    // ones). So:
    expect(tryClaimTrustResponded('win-flood', 'prompt-flood')).toBe(true)
    const sizeAfterFloodSeed = _getTrustDedupLedgerSizeForTests()
    expect(sizeAfterFloodSeed).toBe(4)

    // Hammer the same (win-flood, prompt-flood) many times. Each call is a
    // duplicate of the seed, so each returns false WITHOUT growing the
    // ledger and WITHOUT evicting any of the legitimate older entries.
    for (let i = 0; i < TRUST_DEDUP_MAX_ENTRIES * 4; i++) {
      expect(tryClaimTrustResponded('win-flood', 'prompt-flood')).toBe(false)
    }
    expect(_getTrustDedupLedgerSizeForTests()).toBe(4)

    // The legitimate older entries are still locked (cannot be re-claimed
    // within TTL), proving they survived the duplicate storm.
    expect(tryClaimTrustResponded('win-a', 'oldest')).toBe(false)
    expect(tryClaimTrustResponded('win-b', 'middle')).toBe(false)
    expect(tryClaimTrustResponded('win-c', 'newest')).toBe(false)
  })
})
